phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies (if any)"
  pre_build:
    commands:
      - echo "Cleaning and verifying the project"
      - mvn clean verify -DskipTests

artifacts:
  files:
    - '**/*'
